name: Flutter CI
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: 
  push:
    branches:
      - main

jobs:
  flutter_analyse:
    name: Flutter Analyse
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Clone repo
      - name: Checkout repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      # Checkout FVM config and setup Flutter SDK
      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@v1
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      # flutter pub get
      - name: Install Flutter dependencies
        run: flutter pub get

      # flutter format --set-exit-if-changed .
      - name: Format Code
        run: dart format --set-exit-if-changed .
        continue-on-error: false

      # flutter analyze
      - name: Run Flutter Analyze
        run: flutter analyze
